Add support for `asm!()`
Rahix/avr-device pull request #97
Opened 2022-04-24 17:00 UTC by Patryk27

Closes https://github.com/Rahix/avr-device/issues/91.

# Abstract

Starting from 1.59.0, rustc has been removed support for the `llvm_asm!()` macro, making it impossible to use `avr-device` with newer compilers.

This merge requests adjusts the code, so that it continues to use `llvm_asm!()` on older compilers (such as the infamous `nightly-2021-01-07` one), but switches to `asm!()` on the newer ones.

# Due Diligence

I've checked the code on `nightly-2021-01-07` and a custom-built `rustc` from around yesterday (`b759b2218649016cc40e82bdd6d958e2277ff6d7`), and everything seems to be working correctly.

I've compared the generated LLVM IRs for an application I'm developing, and they are almost identical, with minor changes - e.g.:

`sei`:
```
older rustc:
  tail call addrspace(0) void asm sideeffect "sei", ""() #10, !srcloc !5

newer rustc:
  tail call addrspace(0) void asm sideeffect alignstack "sei", "~{sreg},~{memory}"() #14, !srcloc !6
```

`delay` (granted, comparing those two is a bit tricky - but when put next to another, one can easily spot that there are virtually identical):
```
older rustc:
  ; <avr_hal_generic::delay::Delay<SPEED> as embedded_hal::blocking::delay::DelayMs<u8>>::delay_ms
  ; Function Attrs: minsize nounwind optsize
  define internal fastcc void @"_ZN111_$LT$avr_hal_generic..delay..Delay$LT$SPEED$GT$$u20$as$u20$embedded_hal..blocking..delay..DelayMs$LT$u8$GT$$GT$8delay_ms17had6165a947528b21E"(i8 %ms) unnamed_addr addrspace(1) #1 {
  start:
    %_6.i = zext i8 %ms to i32
    %_5.i = mul nuw nsw i32 %_6.i, 1000
    %iters.i.i = lshr i32 %_5.i, 12
    br label %bb1.i.i

  bb1.i.i:                                          ; preds = %bb3.i.i, %start
    %i.0.i.i = phi i32 [ 0, %start ], [ %1, %bb3.i.i ]
    %_6.i.i = icmp ult i32 %i.0.i.i, %iters.i.i
    br i1 %_6.i.i, label %bb3.i.i, label %"_ZN112_$LT$avr_hal_generic..delay..Delay$LT$SPEED$GT$$u20$as$u20$embedded_hal..blocking..delay..DelayMs$LT$u16$GT$$GT$8delay_ms17h5b05031ffb766e3eE.exit"

  bb3.i.i:                                          ; preds = %bb1.i.i
    %0 = tail call addrspace(0) i16 asm sideeffect "1: sbiw $0,1\0A\09brne 1b", "=w,0"(i16 16375) #10, !srcloc !6
    %1 = add nuw nsw i32 %i.0.i.i, 1
    br label %bb1.i.i

  "_ZN112_$LT$avr_hal_generic..delay..Delay$LT$SPEED$GT$$u20$as$u20$embedded_hal..blocking..delay..DelayMs$LT$u16$GT$$GT$8delay_ms17h5b05031ffb766e3eE.exit": ; preds = %bb1.i.i
    %2 = trunc i32 %_5.i to i16
    %_13.i.i = and i16 %2, 4088
    %3 = icmp eq i16 %_13.i.i, 0
    br i1 %3, label %"_ZN136_$LT$avr_hal_generic..delay..Delay$LT$avr_hal_generic..clock..MHz16$GT$$u20$as$u20$embedded_hal..blocking..delay..DelayUs$LT$u16$GT$$GT$8delay_us17h44b9a0c44d3cc170E.exit", label %4

  4:                                                ; preds = %"_ZN112_$LT$avr_hal_generic..delay..Delay$LT$SPEED$GT$$u20$as$u20$embedded_hal..blocking..delay..DelayMs$LT$u16$GT$$GT$8delay_ms17h5b05031ffb766e3eE.exit"
    %5 = shl nuw nsw i16 %_13.i.i, 2
    %6 = add nsw i16 %5, -5
    %7 = tail call addrspace(0) i16 asm sideeffect "1: sbiw $0,1\0A\09brne 1b", "=w,0"(i16 %6) #10, !srcloc !6
    br label %"_ZN136_$LT$avr_hal_generic..delay..Delay$LT$avr_hal_generic..clock..MHz16$GT$$u20$as$u20$embedded_hal..blocking..delay..DelayUs$LT$u16$GT$$GT$8delay_us17h44b9a0c44d3cc170E.exit"

  "_ZN136_$LT$avr_hal_generic..delay..Delay$LT$avr_hal_generic..clock..MHz16$GT$$u20$as$u20$embedded_hal..blocking..delay..DelayUs$LT$u16$GT$$GT$8delay_us17h44b9a0c44d3cc170E.exit": ; preds = %"_ZN112_$LT$avr_hal_generic..delay..Delay$LT$SPEED$GT$$u20$as$u20$embedded_hal..blocking..delay..DelayMs$LT$u16$GT$$GT$8delay_ms17h5b05031ffb766e3eE.exit", %4
    ret void
  }

newer rustc:
  ; <avr_hal_generic::delay::Delay<SPEED> as embedded_hal::blocking::delay::DelayMs<u8>>::delay_ms
  ; Function Attrs: minsize nounwind optsize
  define internal fastcc void @"_ZN111_$LT$avr_hal_generic..delay..Delay$LT$SPEED$GT$$u20$as$u20$embedded_hal..blocking..delay..DelayMs$LT$u8$GT$$GT$8delay_ms17hc55ec8902c9f4e0dE"(i8 %ms) unnamed_addr addrspace(1) #1 {
  start:
    %_6.i = zext i8 %ms to i32
    %_5.i = mul nuw nsw i32 %_6.i, 1000
    %iters.i.i = lshr i32 %_5.i, 12
    br label %bb1.i.i

  bb1.i.i:                                          ; preds = %bb2.i.i, %start
    %i.0.i.i = phi i32 [ 0, %start ], [ %1, %bb2.i.i ]
    %_6.i.i = icmp ult i32 %i.0.i.i, %iters.i.i
    br i1 %_6.i.i, label %bb2.i.i, label %"_ZN112_$LT$avr_hal_generic..delay..Delay$LT$SPEED$GT$$u20$as$u20$embedded_hal..blocking..delay..DelayMs$LT$u16$GT$$GT$8delay_ms17haed95ea1aa6a52baE.exit"

  bb2.i.i:                                          ; preds = %bb1.i.i
    %0 = tail call addrspace(0) i16 asm sideeffect alignstack "1:\0Asbiw ${0}, 1\0Abrne 1b", "=&r,0,~{sreg},~{memory}"(i16 16375) #14, !srcloc !7
    %1 = add nuw nsw i32 %i.0.i.i, 1
    br label %bb1.i.i

  "_ZN112_$LT$avr_hal_generic..delay..Delay$LT$SPEED$GT$$u20$as$u20$embedded_hal..blocking..delay..DelayMs$LT$u16$GT$$GT$8delay_ms17haed95ea1aa6a52baE.exit": ; preds = %bb1.i.i
    %2 = trunc i32 %_5.i to i16
    %_13.i.i = and i16 %2, 4088
    %3 = icmp eq i16 %_13.i.i, 0
    br i1 %3, label %"_ZN136_$LT$avr_hal_generic..delay..Delay$LT$avr_hal_generic..clock..MHz16$GT$$u20$as$u20$embedded_hal..blocking..delay..DelayUs$LT$u16$GT$$GT$8delay_us17h0521e69a4102ac89E.exit", label %4

  4:                                                ; preds = %"_ZN112_$LT$avr_hal_generic..delay..Delay$LT$SPEED$GT$$u20$as$u20$embedded_hal..blocking..delay..DelayMs$LT$u16$GT$$GT$8delay_ms17haed95ea1aa6a52baE.exit"
    %5 = shl nuw nsw i16 %_13.i.i, 2
    %6 = add nsw i16 %5, -5
    %7 = tail call addrspace(0) i16 asm sideeffect alignstack "1:\0Asbiw ${0}, 1\0Abrne 1b", "=&r,0,~{sreg},~{memory}"(i16 %6) #14, !srcloc !7
    br label %"_ZN136_$LT$avr_hal_generic..delay..Delay$LT$avr_hal_generic..clock..MHz16$GT$$u20$as$u20$embedded_hal..blocking..delay..DelayUs$LT$u16$GT$$GT$8delay_us17h0521e69a4102ac89E.exit"

  "_ZN136_$LT$avr_hal_generic..delay..Delay$LT$avr_hal_generic..clock..MHz16$GT$$u20$as$u20$embedded_hal..blocking..delay..DelayUs$LT$u16$GT$$GT$8delay_us17h0521e69a4102ac89E.exit": ; preds = %"_ZN112_$LT$avr_hal_generic..delay..Delay$LT$SPEED$GT$$u20$as$u20$embedded_hal..blocking..delay..DelayMs$LT$u16$GT$$GT$8delay_ms17haed95ea1aa6a52baE.exit", %4
    ret void
  }
```

The compiled binary seems to be working correctly on an Atmega328p, too.

# Follow-ups

I've also got a similar set of changes to `avr-hal`, I'll try pushing the merge request in a few minutes :-)

2022-04-24 17:05 UTC, Patryk27 commented on README.md
> +cargo install svd2rust --version 0.19.0
Otherwise `cargo` fails with:
```
error: the `--vers` provided, `0.19`, is not a valid semver version: cannot parse '0.19' as a semver
```

2022-04-26 08:32 UTC, Rahix requested changes
Hey, thank you so much for the PR, this is really great!  There is just one thing I'd like to be different, see comments below :)

2022-04-26 08:33 UTC, Rahix commented on README.md
> +cargo install svd2rust --version 0.19.0
Interesting, thanks for spotting!

2022-04-26 15:48 UTC, Patryk27 commented on build.rs
> +    println!(r#"cargo:rustc-cfg=feature="asm""#);
Sure! 🙂

2022-04-26 15:48 UTC, Patryk27 commented on src/asm.rs
> +        if #[cfg(all(target_arch = "avr", feature = "asm"))] {
kk, changed 🙂

2022-04-26 19:25 UTC, merged